name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    name: PHP linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2
      - name: Run PHP lint
        run: composer ci:php:lint
  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader
      - name: Run command
        run: composer ci:php:cs-fixer
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader
      - name: Run Unit tests
        run: composer ci:test:unit
